### ISSUE TITLE
Consider changing backend DB to a collection of files

### ISSUE THREAD

**Issue by mcastorina** [mcastorina/poster#11]
| Backend | Pros | Cons |
| --- | --- | --- |
| DB | foreign key constraints | must interact with data through poster |
|  | one place for all data | |
|  | support for complex queries | |
|  | code is simple | |
| Files | user can CRUD outside of poster | can have lots of files |
|  | sharing resources is easier | code must manually check for conflicts |

**Comment by mcastorina** [comment]
To avoid lots of files, many yaml files can be combined into one like so:

```
requests:
- name: test
  method: GET
  url: http://:host/
  environment:
    name: local
  body: ""
  headers:
  - key: Authorization
    value: :auth
  - key: Content-Type
    value: application/json
variables:
- name: host
  value: localhost:8080
  environment:
    name: local
  type: const
  generator: ""
```

or 

```
resource: request
name: test
method: GET
url: http://:host/
environment:
  name: local
body: ""
headers:
- key: Authorization
  value: :auth
- key: Content-Type
  value: application/json
---
resource: variable
name: host
value: localhost:8080
environment:
  name: local
type: const
generator: ""
```
